// Mocks generated by Mockito 5.0.10 from annotations
// in erpgestao/test/app/modules/home/domain/usescases/get_financial_closed_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:erpgestao/app/core/error/failures.dart' as _i5;
import 'package:erpgestao/app/modules/home/data/model/home_sales_payment_type_model.dart'
    as _i6;
import 'package:erpgestao/app/modules/home/domain/repositories/home_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.HomeSalesPaymentTypeModel>>>
      getFinancialClosed({
    String? initialDate,
    String? finalDate,
    String? terminal,
  }) =>
          (super.noSuchMethod(
              Invocation.method(#getFinancialClosed, [],
                  {#initialDate: initialDate, #finalDate: finalDate}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.HomeSalesPaymentTypeModel>>>.value(
                      _FakeEither<_i5.Failure,
                          List<_i6.HomeSalesPaymentTypeModel>>())) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.HomeSalesPaymentTypeModel>>>);
}
