// Mocks generated by Mockito 5.0.10 from annotations
// in frontend/test/app/modules/auth/domain/usescases/login_email_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:frontend/app/core/error/failures.dart' as _i5;
import 'package:frontend/app/modules/auth/data/model/auth_model.dart' as _i6;
import 'package:frontend/app/modules/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthModel>> loginEmail(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #loginEmail, [], {#username: username, #password: password}),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.AuthModel>>.value(
                  _FakeEither<_i5.Failure, _i6.AuthModel>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthModel>>);
}
